### ISSUE TITLE
Mouse movement isnt smooth at high framerates

### ISSUE THREAD

**Issue by Lagahan** [OpenXRay/xray-16#553] opened 2020-03-04 22:33 UTC
As in title, mouse input when the game is in exclusive fullscreen or when the window is in focus in windowed mode is not smooth - it feels like its taking input at 60Hz rather than the actual framerate.

Just to clarify - its not stuttering but it feels like its updating slower than the rest of the game. Strafing or moving around or using the arrow keys to look is as smooth as you'd expect for the framerate.

Oddly when you alt tab so that the game isn't in focus but move your mouse over the game window (with "Always active: on") camera rotation is as smooth as expected. 

I'm assuming this is a quirk of porting the engine to use SDL - is the update rate for mouse input capped at 60Hz or something? Thats what it feels like, although without the input lag.

Always visible at high refreshrates - I play at 240Hz, but its also visible at 120Hz as well.

 - OS: Windows 10 1909
 - OpenXRay: 558
 - Mouse's USB polling rate is 1000Hz, incase that might be influencing this.

**Comment by Xottab-DUTY** [comment] 2020-03-05 02:45
Probably, there are several reasons of that:
1. Because of SDL2 layer, input system can be quite slower and it is choking at very low FPS. Because of that, for optimization purpose, maximum mouse update events in the engine were limited to 256 events per frame. ~~But it seems that this is not the reason, since limitation doesn't affect the camera.~~
2. Because of the engine architecture, in-game cursor is bound to the current FPS both in the original engine and OpenXRay.
3. In addition to the previous, in OpenXRay in-game cursor is also bound to the system's cursor position. **Could it be that the system cursor is locked to 60hz?**

**Comment by eagleivg** [comment] 2020-03-05 07:47
4. Also this is can be multi-thread problem. Try build engine from https://github.com/eagleivg/xray-16 - this fork use old single-thread input.

**Comment by Lagahan** [comment] 2020-03-05 09:13
"In addition to the previous, in OpenXRay in-game cursor is also bound to the system's cursor position. Could it be that the system cursor is locked to 60hz?"

Thats the strange thing, when the game is out of focus and you mouse over the window the camera / player rotates smoother than when the input is exclusive. System cursor runs at the the refresh rate of the screen.

I'll try to get a build environment set up when I get home from work this evening and build that fork.

**Comment by Xottab-DUTY** [comment] 2020-03-05 09:38
> But it seems that this is not the reason, since limitation doesn't affect the camera.

Oh, it seems that I have misread what you're saying and now I'm unsure about that.

> when the game is out of focus and you mouse over the window the camera / player rotates smoother than when the input is exclusive.

I can confirm this on Windows. There's a problem in SDL itself that causes performance drops when we use exclusive input mode for mouse. The game was unplayable on low FPS because of that.
To fix that, along with limiting events to 256, I also made multithreaded input update, but the problem wasn't fully fixed and turned out into micro lag spikes (better than before, but still bad) and problems with mouse input described above.

For Windows this can be fixed with just using Windows API's directly. Probably the same goes for Linux.. But that's not universal :)

We will think on how to fix input problems with SDL2 and also we will switch to using platform-specific API's directly if such platform-specific implementation is available. (since it's always faster than using SDL2)

**Comment by Xottab-DUTY** [comment] 2020-03-16 07:08
Should be fixed with c81fed8b0a6a6b269e07e9a55fecfff588db5f1b and a563181714df16006095a44f7c5aa1162afae7e8.

@Lagahan, please, try a new build: https://github.com/OpenXRay/xray-16/actions/runs/55055992

**Comment by Lagahan** [comment] 2020-03-20 20:42
> 
> 
> Should be fixed with [c81fed8](https://github.com/OpenXRay/xray-16/commit/c81fed8b0a6a6b269e07e9a55fecfff588db5f1b) and [a563181](https://github.com/OpenXRay/xray-16/commit/a563181714df16006095a44f7c5aa1162afae7e8).
> 
> @Lagahan, please, try a new build: https://github.com/OpenXRay/xray-16/actions/runs/55055992

That works perfect! Thanks man, sorry for the late reply!

**Comment by Xottab-DUTY** [comment] 2020-03-20 20:44
Cool!

**Closed as completed by Xottab-DUTY** 2020-03-20 20:44 UTC
Labels: Bug, Player Experience
