### ISSUE TITLE
Can't load saves+transit between places in random conditions

### ISSUE THREAD

**Issue by GiulianoB-1** [OpenXRay/xray-16#834] opened 2021-07-02 10:21 UTC
**Describe the bug**
I made a really good progress already in the Stalker clear sky, got to first part in Yantar. I was in the aprogrom before I got to Yantar, I was trying to grind money for upgrading my exoskeleton, in a specific part of the game, when I started saving, a list of specific saves were not loadable, I got crash when got to "synchronizing". I tried many methods to bypass this bug, and successfully got to Yanter, tho now every save is not loadable even in Yanter. I tried to change the renderer from renderer_r4 to Directx 10.1, it worked for some reason, the saves were not loadable, but new saves were successfully loading. Also, using Anti Aliasing causes a weird issue with the light on directx10. I got now to dark valley with a guide, but now using a guide again causes crash. I am confused about what conditions causes those crashes, I am unable to confirm.
**Screenshots**
Directx10 Anti Aliasing issue:
![image](https://user-images.githubusercontent.com/67099534/124259810-9d14c380-db37-11eb-94bf-3bf345b79db2.png)
![image](https://user-images.githubusercontent.com/67099534/124259833-a7cf5880-db37-11eb-823b-72264160bc6d.png)

**BugTrap error report**
The crashes caused by directx11(Error log): 
[OpenXRay_error_report_210702-122106.zip](https://github.com/OpenXRay/xray-16/files/6753924/OpenXRay_error_report_210702-122106.zip)
[OpenXRay_error_report_210701-231729.zip](https://github.com/OpenXRay/xray-16/files/6753932/OpenXRay_error_report_210701-231729.zip)
[OpenXRay_error_report_210701-231051.zip](https://github.com/OpenXRay/xray-16/files/6753993/OpenXRay_error_report_210701-231051.zip)
[OpenXRay_error_report_210702-140135.zip](https://github.com/OpenXRay/xray-16/files/6754249/OpenXRay_error_report_210702-140135.zip)

The crashes caused by directx11(openxray logs):
[openxray_giuliano.log](https://github.com/OpenXRay/xray-16/files/6753944/openxray_giuliano.log)
[xray_giuliano.log](https://github.com/OpenXRay/xray-16/files/6753945/xray_giuliano.log)

**Desktop:**
 - OS: Windows 11
 - OpenXRay build version 822

**Comment by GiulianoB-1** [comment] 2021-07-02 11:02
Got some more weird crashes for unknown reasons when loading save(while using directx10) , also when I loaded a save in Yantar, I got PSI for no reason but after a few moments it disappears. I must mention that the zombies in yantar KEEP SPAWNING RAPIDLY, JEEZZZZZ
[OpenXRay_error_report_210702-140135.zip](https://github.com/OpenXRay/xray-16/files/6754161/OpenXRay_error_report_210702-140135.zip)

P.S:
Bruhhhhh

**Comment by GiulianoB-1** [comment] 2021-07-02 11:22
It seems like the only renderer that won't cause those crashes is Opengl which is unfortunate because it is uncomplete, and pretty unusable(extremely laggy).

**Comment by Xottab-DUTY** [comment] 2021-12-14 01:32
According to the logs, looks like this is a duplicate of #840. We had problems with LuaJIT, affecting both CoP and CS...
Since that issue was fixed, I'm closing this too.

Please, reopen if the issue is still there. (probably, it's better to start a new game)

Also, if you still have issues with renderers or zombies, please, open a new issue. :)

**Closed as completed by Xottab-DUTY** 2021-12-14 01:32 UTC
Labels: Duplicate
