### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by ghost** [OpenXRay/xray-16#215] opened 2018-06-21 06:41 UTC
Hi,

I'm a huge STALKER fan, and I'm playing the game in WINE, which works well enough.
Obviously I'm very much interested in a native Linux port of the game, which would require an OpenGL or Vulkan renderer.

Is this planned?

Regards

**Comment by Xottab-DUTY** [comment] 2018-06-21 07:04
Decision about implementing Vulkan wasn't made. We're thinking on it...

But we already have an OpenGL renderer. It has some bad code and dirty hacks, but it's working at least..


By the way, this is a duplicate of #185

**Closed as completed** 2018-06-30 10:09 UTC
Labels: Duplicate
