### ISSUE TITLE
ЧН крашит при запуске новой игры

### ISSUE THREAD

**Issue by DarkKel** [OpenXRay/xray-16#659] opened 2020-08-21 13:37 UTC
Чистое ЧН 1.5.10, поставлен 558 (последний релиз) опенхр + геймдата для ЧН - при нажатии "новая игра" начинает грузиться и тут же вылет с:

xrEngine.exe caused BREAKPOINT in module "K:\Games\S.T.A.L.K.E.R. CS\bin\xrCore.dll" at 0033:00000000CB745E1C, xrDebug::Fail()+812 byte(s)

лог:

```
OpenXRay Rx64 build 7568, Oct 26 2019
AppVeyor build 558 from commit[443b674ac99c705c8bce2e9ce439f6fe7fed3dd4] branch[HEAD] (built by OpenXRay)
 
command line 

* CPU features: RDTSC, MMX, SSE, SSE2, SSE3, SSE4.1, SSE4.2
* CPU cores/threads: 4/4
* CPU0 current freq: 3600 MHz, max freq: 3600 MHz
* CPU1 current freq: 3600 MHz, max freq: 3600 MHz
* CPU2 current freq: 3600 MHz, max freq: 3600 MHz
* CPU3 current freq: 3600 MHz, max freq: 3600 MHz

Initializing File System...
using fs-ltx fsgame.ltx
FS: 28203 files cached 28 archives, 7316Kb memory used.
Init FileSystem 1.203343 sec
-----loading K:\Games\S.T.A.L.K.E.R. CS\gamedata\configs\system.ltx
-----loading K:\Games\S.T.A.L.K.E.R. CS\gamedata\configs\system.ltx
Starting INPUT device...
No joysticks available
Loading module: xrRender_GL
Loading module: xrRender_R1
Loading module: xrRender_R2
Loading module: xrRender_R3
Loading module: xrRender_R4
Loading module: d3d9
Loading module: d3d9
refCount:pD3D 1
refCount:m_pAdapter 1
refCount:m_pFactory 1
Available render modes[8]:
renderer_r1
renderer_r2a
renderer_r2
renderer_r2.5
renderer_r3
renderer_r4
renderer_gl
Executing config-script "user.ltx"...
[C:\Users\Eraser\DOCUME~1\STALKE~3\user.ltx] successfully loaded.
Selected renderer: renderer_r3
Loading module: xrGame
! Unable to find Software\GSC Game World\STALKER-COP\ in registry
! Player name registry key (InstallUserName) not found !
Initializing Engine...
Executing config-script "K:\Games\S.T.A.L.K.E.R. CS\gamedata\configs\default_controls.ltx"...
! Can't find a key name for kUNKNOWN
! Can't find a key name for kINTERNATIONAL1
! Can't find a key name for kINTERNATIONAL2
! Can't find a key name for kYEN
! Can't find a key name for kINTERNATIONAL4
! Can't find a key name for kINTERNATIONAL5
! Can't find a key name for kINTERNATIONAL6
! Can't find a key name for kINTERNATIONAL7
! Can't find a key name for kINTERNATIONAL8
! Can't find a key name for kINTERNATIONAL9
! Can't find a key name for kHANGUL
! Can't find a key name for kHANJA
! Can't find a key name for kKATAKANA
! Can't find a key name for kHIRAGANA
! Can't find a key name for kZENHANKAKU
! Can't find a key name for kLANG6
! Can't find a key name for kLANG7
! Can't find a key name for kLANG8
! Can't find a key name for kLANG9
! Can't find a key name for kAPP1
! Can't find a key name for kAPP2
! [ActionNameToPtr] cant find corresponding 'id' for 'alife_command'
[K:\Games\S.T.A.L.K.E.R. CS\gamedata\configs\default_controls.ltx] successfully loaded.
Executing config-script "user.ltx"...
Executing config-script "K:\Games\S.T.A.L.K.E.R. CS\gamedata\configs\rspec_high.ltx"...
[K:\Games\S.T.A.L.K.E.R. CS\gamedata\configs\rspec_high.ltx] successfully loaded.
! Unknown command:  bemsg
! [ActionNameToPtr] cant find corresponding 'id' for 'alife_command'
! Unknown command:  g_always_run
! Unknown command:  mm_net_filter_battleye
! Unknown command:  mm_net_use_battleye
! Unknown command:  r1_no_detail_textures
[C:\Users\Eraser\DOCUME~1\STALKE~3\user.ltx] successfully loaded.
SOUND: OpenAL: enumerate devices...
SOUND: OpenAL: EnumerationExtension Present
dir[0]=K:\Games\S.T.A.L.K.E.R. CS\bin\
dir[1]=K:\Games\S.T.A.L.K.E.R. CS\
dir[2]=K:\Games\S.T.A.L.K.E.R. CS\bin\
dir[3]=C:\WINDOWS\system32\
CleanDeviceSpecifierList
CleanDeviceSpecifierList Generic Software
devices Generic Software
SOUND: OpenAL: system  default SndDevice name is Generic Software
SOUND: OpenAL: All available devices:
1. Generic Software, Spec Version 1.1 (default) eax[2] efx[yes] xram[no]
SOUND: Selected device is Generic Software
* sound: EAX 2.0 extension: absent
* sound: EAX 2.0 deferred: absent
* sound : cache: 65537 kb, 4856 lines, 13820 bpl
Starting RENDER device...
* GPU [vendor:10DE]-[device:1C82]: NVIDIA GeForce GTX 1050 Ti
* CREATE: DeviceREF: 1
*   Texture memory: 4018 M
* GPU shading: vs(0/4.0/40), ps(0/4.0/40)
* GPU vertex cache: unrecognized, 24
* NVidia MGPU: Logical(1), Physical(1)
* AGS: Initialization failed (3)
* Starting rendering as 1-GPU.
* DVB created: 4096K
* DIB created: 512K
! Version conflict in shader 'def_shaders\def_vertex'
! Version conflict in shader 'default'
! Version conflict in shader 'effects\lightplanes'
! Renderer doesn't support blender 'effects\shadow_world'
! Version conflict in shader 'models\lightplanes'
! Version conflict in shader 'models\model'
! Version conflict in shader 'models\model_aref'
! Version conflict in shader 'models\model_fur'
! Version conflict in shader 'models\pautina'
! Version conflict in shader 'models\selflight'
! Version conflict in shader 'models\selflight_det'
! Version conflict in shader 'models\selflightl'
! Version conflict in shader 'models\transparent'
! Version conflict in shader 'models\xanomaly'
! Version conflict in shader 'models\xdistort'
! Version conflict in shader 'models\xdistortcolor'
! Version conflict in shader 'models\xdistortcolorl'
! Version conflict in shader 'models\xdistortinv'
! Version conflict in shader 'models\xmonolith'
! Version conflict in shader 'models\xwindows'
! Version conflict in shader 'selflight'
* HWDST/PCF supported and used
Starting engine...
! Unable to find Software\GSC Game World\STALKER-COP\ in registry
! Player name registry key (InstallUserName) not found !
! Unable to find Software\GSC Game World\STALKER-COP\ in registry
Loading module: AnselSDK64
! Nvidia Ansel:: failed to load AnselSDKxx.dll
! Task done after abnormal execution time [-881598176ms] in [GMLib.Load()]
! Can't find sound 'characters_voice\scenario\video\intro_gsc'
! Can't find sound 'characters_voice\scenario\video\ds_black'
! Invalid ogg-comment version, file:  K:\Games\S.T.A.L.K.E.R. CS\gamedata\sounds\characters_voice\scenario\video\ati.ogg
intro_start intro_logo
intro_delete ::update_logo_intro
* [ Windows ]: free[-4992612 K], reserved[4379812 K], committed[612736 K]
* [ Render ]: textures[16 K]
* [ x-ray  ]: process heap[428760 K]
* [ x-ray  ]: economy: strings[9366 K], smem[0 K]
! [ActionNameToPtr] cant find corresponding 'id' for 'alife_command'
! [ActionNameToPtr] cant find corresponding 'id' for 'alife_command'
*  0.0 : [   3] $null
*  0.0 : [   1] $user$NVHHGGTex
*  0.0 : [   5] $user$NVjitterTex
*  0.0 : [   8] $user$Texture_color
*  0.0 : [   1] $user$Texture_color_out
*  0.0 : [   7] $user$Texture_obstacles
*  0.0 : [   3] $user$Texture_obstvelocity
*  0.0 : [   3] $user$Texture_pressure
*  0.0 : [   2] $user$Texture_tempscalar
*  0.0 : [   3] $user$Texture_tempvector
*  0.0 : [   5] $user$Texture_velocity0
*  0.0 : [   4] $user$Texture_velocity1
*  0.0 : [   3] $user$accum
*  0.0 : [   1] $user$accum_temp
*  0.0 : [   5] $user$albedo
*  0.0 : [   4] $user$bloom1
*  0.0 : [   2] $user$bloom2
*  0.0 : [   1] $user$cmap0
*  0.0 : [   1] $user$cmap1
*  0.0 : [   3] $user$edgeTex
*  0.0 : [   2] $user$env_s0
*  0.0 : [   2] $user$env_s1
*  0.0 : [   1] $user$generic
*  0.0 : [   6] $user$generic0
*  0.0 : [   4] $user$generic1
*  0.0 : [   2] $user$generic2
*  0.0 : [   4] $user$jitter_0
*  0.0 : [   2] $user$jitter_1
*  0.0 : [   1] $user$jitter_2
*  0.0 : [   1] $user$jitter_3
*  0.0 : [   1] $user$jitter_4
*  0.0 : [   1] $user$jitter_mipped
*  0.0 : [   2] $user$lum_t64
*  0.0 : [   3] $user$lum_t8
*  0.0 : [   1] $user$luminance_0
*  0.0 : [   1] $user$luminance_1
*  0.0 : [   8] $user$material
*  0.0 : [ 103] $user$position
*  0.0 : [   3] $user$rayCastTex
*  0.0 : [   6] $user$rayDataTex
*  0.0 : [   2] $user$rayDataTexSmall
*  0.0 : [   1] $user$sky0
*  0.0 : [   1] $user$sky1
*  0.0 : [   7] $user$smap_depth
*  0.0 : [   1] $user$smap_depth_minmax
*  0.0 : [   1] $user$smap_surf
*  0.0 : [   7] $user$tonemap
*  0.0 : [   2] $user$tonemap_src
*  0.0 : [   2] act\act_controller_hit1
*  0.0 : [   2] fx\fx_flare1
*  0.0 : [   1] fx\fx_flare2
*  0.0 : [   1] fx\fx_flare3
*  0.0 : [   2] fx\fx_gradient
*  0.0 : [   2] fx\fx_gradient1
*  0.0 : [   1] fx\fx_lightning
*  0.0 : [   1] fx\fx_noise
*  0.0 : [   1] fx\fx_noise2
*  0.0 : [   1] fx\fx_rain
*  0.0 : [   1] fx\fx_rainsplash1
*  0.0 : [   2] fx\fx_sun
*  0.0 : [   1] fx\fx_sun_rise
*  0.0 : [   1] fx\fx_thunderbolts_gradient
*  0.0 : [   1] fx\fx_thunderbolts_gradient_surge
*  0.0 : [   2] fx\fx_volumefog1
*  0.0 : [   2] glow\glow_fire1
*  0.0 : [   2] glow\glow_orange
*  0.0 : [   2] glow\glow_orange2
*  0.0 : [   2] glow\glow_orange_bright
*  0.0 : [   2] glow\glow_white
*  0.0 : [   2] internal\internal_fireTransferFunction
*  0.0 : [   3] lights\lights_spot01
*  0.0 : [   2] pfx\pfx_ani-explosion-02
*  0.0 : [   2] pfx\pfx_ani-explosion-02-b-a
*  0.0 : [   2] pfx\pfx_ani-explosion-02a
*  0.0 : [   2] pfx\pfx_ani-fire01
*  0.0 : [   2] pfx\pfx_ani-smoke-01
*  0.0 : [   2] pfx\pfx_anomaly_1
*  0.0 : [   2] pfx\pfx_anomaly_16
*  0.0 : [   2] pfx\pfx_anomaly_17
*  0.0 : [   2] pfx\pfx_anomaly_18
*  0.0 : [   2] pfx\pfx_anomaly_19
*  0.0 : [   2] pfx\pfx_anomaly_2
*  0.0 : [   2] pfx\pfx_anomaly_21
*  0.0 : [   2] pfx\pfx_anomaly_23
*  0.0 : [   2] pfx\pfx_anomaly_2_green
*  0.0 : [   2] pfx\pfx_anomaly_3
*  0.0 : [   2] pfx\pfx_anomaly_4
*  0.0 : [   2] pfx\pfx_anomaly_5
*  0.0 : [   2] pfx\pfx_anomaly_6
*  0.0 : [   2] pfx\pfx_anomaly_7
*  0.0 : [   2] pfx\pfx_anomaly_8
*  0.0 : [   2] pfx\pfx_anomaly_88
*  0.0 : [   2] pfx\pfx_bloodsplash1
*  0.0 : [   2] pfx\pfx_bloodsplash2
*  0.0 : [   2] pfx\pfx_blurry_cloud
*  0.0 : [   2] pfx\pfx_brick
*  0.0 : [   2] pfx\pfx_bubble
*  0.0 : [   2] pfx\pfx_bubble_1
*  0.0 : [   2] pfx\pfx_bubble_water
*  0.0 : [   2] pfx\pfx_concretedebris_01
*  0.0 : [   2] pfx\pfx_concretepuffs_01
*  0.0 : [   1] pfx\pfx_dist2
*  0.0 : [   1] pfx\pfx_dist2inv
*  0.0 : [   1] pfx\pfx_dist3
*  0.0 : [   1] pfx\pfx_dist4
*  0.0 : [   1] pfx\pfx_dist8
*  0.0 : [   1] pfx\pfx_dist9
*  0.0 : [   1] pfx\pfx_dist_teleport
*  0.0 : [   1] pfx\pfx_distort_anomaly
*  0.0 : [   2] pfx\pfx_distortion
*  0.0 : [   2] pfx\pfx_explotions_2
*  0.0 : [   2] pfx\pfx_explotions_3
*  0.0 : [   2] pfx\pfx_explotions_4
*  0.0 : [   2] pfx\pfx_explotions_smoke
*  0.0 : [   2] pfx\pfx_flame
*  0.0 : [   2] pfx\pfx_flame_01
*  0.0 : [   2] pfx\pfx_flamefx_01
*  0.0 : [   2] pfx\pfx_flash_01
*  0.0 : [   2] pfx\pfx_flash_05
*  0.0 : [   2] pfx\pfx_flash_07
*  0.0 : [   2] pfx\pfx_gologramma
*  0.0 : [   2] pfx\pfx_leaves_01
*  0.0 : [   2] pfx\pfx_leaves_02
*  0.0 : [   2] pfx\pfx_light1
*  0.0 : [   2] pfx\pfx_light3
*  0.0 : [   2] pfx\pfx_light4
*  0.0 : [   1] pfx\pfx_lighting_stancia_01
*  0.0 : [   1] pfx\pfx_lighting_stancia_02
*  0.0 : [   2] pfx\pfx_lightning_01
*  0.0 : [   2] pfx\pfx_lightning_02
*  0.0 : [   2] pfx\pfx_ligth_6
*  0.0 : [   2] pfx\pfx_plasma
*  0.0 : [   2] pfx\pfx_shells1
*  0.0 : [   2] pfx\pfx_skinsplash1
*  0.0 : [   2] pfx\pfx_smoke_a
*  0.0 : [   2] pfx\pfx_smoke_b
*  0.0 : [   2] pfx\pfx_smokepuffs1
*  0.0 : [   2] pfx\pfx_smokepuffs2
*  0.0 : [   2] pfx\pfx_spark_01
*  0.0 : [   2] pfx\pfx_sparks
*  0.0 : [   2] pfx\pfx_specks
*  0.0 : [   2] pfx\pfx_specks_poison
*  0.0 : [   2] pfx\pfx_spikey_star
*  0.0 : [   2] pfx\pfx_splash3
*  0.0 : [   2] pfx\pfx_splash_01
*  0.0 : [   2] pfx\pfx_splash_02
*  0.0 : [   2] pfx\pfx_step_blood
*  0.0 : [   2] pfx\pfx_stonedebris1
*  0.0 : [   2] pfx\pfx_stonedebris2
*  0.0 : [   2] pfx\pfx_synus
*  0.0 : [   2] pfx\pfx_teleport
*  0.0 : [   2] pfx\pfx_test_textures
*  0.0 : [   2] pfx\pfx_vehglassdebris_01
*  0.0 : [   2] pfx\pfx_vehmetaldebris_01
*  0.0 : [   2] pfx\pfx_water_wave
*  0.0 : [   2] pfx\pfx_woodchips1
*  0.0 : [   2] pfx\pfx_woodchips3
*  0.0 : [   2] prop\prop_fake_bed_fireplace
*  0.0 : [   2] prop\prop_provod_02
*  0.0 : [   5] sky\sky_12_vibros_cube
*  0.0 : [   5] sky\sky_12_vibros_cube#small
*  0.0 : [  24] sky\sky_13_cube
*  0.0 : [  24] sky\sky_13_cube#small
*  0.0 : [  16] sky\sky_13_cube_night
*  0.0 : [  16] sky\sky_13_cube_night#small
*  0.0 : [  12] sky\sky_13_vibros_cube
*  0.0 : [  12] sky\sky_13_vibros_cube#small
*  0.0 : [  10] sky\sky_14_cube
*  0.0 : [  10] sky\sky_14_cube#small
*  0.0 : [   4] sky\sky_17_clouds_cube
*  0.0 : [   4] sky\sky_17_clouds_cube#small
*  0.0 : [   4] sky\sky_17_cube
*  0.0 : [   4] sky\sky_17_cube#small
*  0.0 : [   8] sky\sky_18_cube
*  0.0 : [   8] sky\sky_18_cube#small
*  0.0 : [  11] sky\sky_19_cube
*  0.0 : [  11] sky\sky_19_cube#small
*  0.0 : [   4] sky\sky_1_clouds_cube
*  0.0 : [   4] sky\sky_1_clouds_cube#small
*  0.0 : [   4] sky\sky_20_clouds_cube
*  0.0 : [   4] sky\sky_20_clouds_cube#small
*  0.0 : [   4] sky\sky_20_cube
*  0.0 : [   4] sky\sky_20_cube#small
*  0.0 : [   4] sky\sky_2_clouds_cube
*  0.0 : [   4] sky\sky_2_clouds_cube#small
*  0.0 : [   4] sky\sky_2_cube
*  0.0 : [   4] sky\sky_2_cube#small
*  0.0 : [  12] sky\sky_3_cube
*  0.0 : [  12] sky\sky_3_cube#small
*  0.0 : [   3] sky\sky_4_cube
*  0.0 : [   3] sky\sky_4_cube#small
*  0.0 : [  30] sky\sky_5_cube
*  0.0 : [  30] sky\sky_5_cube#small
*  0.0 : [   7] sky\sky_6_cube
*  0.0 : [   7] sky\sky_6_cube#small
*  0.0 : [  13] sky\sky_7_cube
*  0.0 : [  13] sky\sky_7_cube#small
*  0.0 : [   8] sky\sky_8_cube
*  0.0 : [   8] sky\sky_8_cube#small
*  0.0 : [  47] sky\sky_9_cube
*  0.0 : [  47] sky\sky_9_cube#small
*  0.0 : [ 234] sky\sky_oblaka
*  0.0 : [   1] ui\ui_hud
*  0.0 : [   1] ui\ui_load
*  0.0 : [   1] ui_listline2
*  0.0 : [   1] water\water_SBumpVolume
*  0.0 : [   1] water\water_flowing_nmap
*  0.0 : [   1] water\water_normal
*  0.0 : [   1] wm\wm_blood_1
*  0.0 : [   1] wm\wm_blood_1_1
*  0.0 : [   1] wm\wm_blood_1_2
*  0.0 : [   1] wm\wm_blood_1_3
*  0.0 : [   1] wm\wm_blood_drop_4
*  0.0 : [   1] wm\wm_bullet_asfalt_1
*  0.0 : [   1] wm\wm_bullet_asfalt_2
*  0.0 : [   1] wm\wm_bullet_asfalt_3
*  0.0 : [   1] wm\wm_bullet_brick_1
*  0.0 : [   1] wm\wm_bullet_brick_2
*  0.0 : [   1] wm\wm_bullet_concrete
*  0.0 : [   1] wm\wm_bullet_concrete_1
*  0.0 : [   1] wm\wm_bullet_concrete_2
*  0.0 : [   1] wm\wm_bullet_concrete_4
*  0.0 : [   1] wm\wm_bullet_concrete_5
*  0.0 : [   1] wm\wm_bullet_concrete_6
*  0.0 : [   1] wm\wm_bullet_concrete_7
*  0.0 : [   1] wm\wm_bullet_glass01
*  0.0 : [   1] wm\wm_bullet_glass02
*  0.0 : [   1] wm\wm_bullet_glass03
*  0.0 : [   1] wm\wm_bullet_glass04
*  0.0 : [   1] wm\wm_bullet_ground
*  0.0 : [   1] wm\wm_bullet_ground_1
*  0.0 : [   1] wm\wm_bullet_ground_2
*  0.0 : [   1] wm\wm_bullet_metall_thik
*  0.0 : [   1] wm\wm_bullet_metall_thik_1
*  0.0 : [   1] wm\wm_bullet_metall_thik_2
*  0.0 : [   1] wm\wm_bullet_metall_thik_3
*  0.0 : [   1] wm\wm_bullet_metall_thin
*  0.0 : [   1] wm\wm_bullet_metall_thin_1
*  0.0 : [   1] wm\wm_bullet_metall_thin_2
*  0.0 : [   1] wm\wm_bullet_metall_thin_3
*  0.0 : [   1] wm\wm_bullet_metall_thin_4
*  0.0 : [   1] wm\wm_bullet_wood
*  0.0 : [   1] wm\wm_bullet_wood_1
*  0.0 : [   1] wm\wm_bullet_wood_2
*  0.0 : [   1] wm\wm_bullet_wood_3
*  0.0 : [   1] wm\wm_bullet_wood_4
*  0.0 : [   1] wm\wm_bullet_wood_5
*  0.0 : [   1] wm\wm_bullet_wood_6
*  0.0 : [   1] wm\wm_bullet_wood_7
*  0.0 : [   1] wm\wm_bullet_wood_8
*  0.0 : [   1] wm\wm_bullet_wood_9
*  0.0 : [   1] wm\wm_knife_dead
*  0.0 : [   1] wm\wm_knife_horiz
*  0.0 : [   1] wm\wm_knife_horiz_blood
*  0.0 : [   1] wm\wm_knife_horiz_blood1
*  0.0 : [   1] wm\wm_knife_horiz_metal
*  0.0 : [   1] wm\wm_knife_horiz_ston
*  0.0 : [   1] wm\wm_knife_wood
*  0.0 : [   1] wm\wm_knife_wood1
*  0.0 : [   1] wm\wm_knife_wood2
* 16.1 : [   1] ui\ui_font_hud_01
* 32.1 : [   1] ui\ui_magnifier2
* 33.0 : [   1] ui\ui_ani_cursor
* 64.1 : [   1] ui\ui_font_console_02
* 64.1 : [   1] ui\ui_font_hud_02
* 128.0 : [   1] ui\ui_mm_rug02
* 128.1 : [   1] ui\ui_font_arial_14_1600
* 256.0 : [   1] ui\ui_mm2_pautina
* 256.1 : [   1] ui\ui_font_letter_16_1600
* 256.1 : [   1] ui\ui_font_letter_18_1600
* 512.1 : [   1] ui\ui_font_graff_19_1600
* 512.1 : [   1] ui\ui_font_graff_22_1600
* 1024.0 : [   1] ui\ui_mm2_back_video
* 1024.1 : [   1] ui\ui_font_graff_32_1600
* 1024.1 : [   1] ui\ui_font_letter_25_1600
* 1024.1 : [   1] ui\ui_ingame2_back_01
* 1024.1 : [   1] ui\ui_ingame2_back_add2_w
* 1024.1 : [   1] ui\ui_ingame2_back_add_w
* 1024.1 : [   1] ui\ui_mainmenu2
* 1720.0 : [   1] ui\ui_mm_window_back_crop
* 2048.1 : [   1] ui\ui_font_graff_50_1600
* 4096.1 : [   1] ui\ui_common
* phase time: 0 ms
* phase cmem: 470272 K
Loading sounds...
! Invalid ogg-comment version, file:  K:\Games\S.T.A.L.K.E.R. CS\gamedata\sounds\characters_voice\scenario\video\ati.ogg
Loading objects...
Loading models...
Loading textures...
! Can't find texture 'ui_listline2'
* [prefetch] time:   1055 ms
* [prefetch] memory: 63504 Kb
! Unable to find Software\GSC Game World\STALKER-COP\ in registry
! Player name registry key (InstallUserName) not found !
* phase time: 1084 ms
* phase cmem: 533884 K
! [LUA][ERROR]  ERROR: There are no sound collection with path: characters_voice\scenario\agroprom\agr_base_commander_reward_pda
stack traceback:
	K:\Games\S.T.A.L.K.E.R. CS\gamedata\scripts\_g.script:974: in function 'abort'
	...es\S.T.A.L.K.E.R. CS\gamedata\scripts\sound_theme.script:364: in function <...es\S.T.A.L.K.E.R. CS\gamedata\scripts\sound_theme.script:326>
	[C]: in function 'actor_sound'
	...es\S.T.A.L.K.E.R. CS\gamedata\scripts\sound_theme.script:774: in function 'load_sound'
	K:\Games\S.T.A.L.K.E.R. CS\gamedata\scripts\_g.script:1148: in function <K:\Games\S.T.A.L.K.E.R. CS\gamedata\scripts\_g.script:1077>
 
FATAL ERROR
 
[error] Expression    : 0
[error] Function      : ErrorLog
[error] File          : C:\projects\xray-16\src\xrScriptEngine\ScriptEngineScript.cpp
[error] Line          : 40
[error] Description   : ERROR: There are no sound collection with path: characters_voice\scenario\agroprom\agr_base_commander_reward_pda
```

**Comment by Xottab-DUTY** [comment] 2020-08-28 02:15
This issue was relatively recently fixed (in the commit https://github.com/OpenXRay/xray-16/commit/384a5d5e9c8fae35fa9ac7e0e91b3986e26853e3) but the fixed version has not been released yet.

Though, there's a pre-release which can be used: [July Preview](https://github.com/OpenXRay/xray-16/releases/tag/730-july-preview)

Since the issue is fixed technically, I assume I can close this issue.

**Closed as duplicate by Xottab-DUTY** 2020-08-28 02:15 UTC
Labels: Bug, Core, Clear Sky

**Comment by 0xA50C1A1** [comment] 2023-01-07 15:05
Баг до сих пор присутствует.
